### PR TITLE
package.json: Updated for npm

### PR DESCRIPTION
**Pull request by sompylasar**
* Renamed package to `epoch-charting` to avoid clashing with existing node module `epoch`.
* Added description, keywords, homepage, author, licenses, repository. 
* Changed `dependencies` to `devDependencies`, changed the version prefixes to caret `^` (i.e. compatible).
* Added `d3` to package `dependencies`.

### CODE REVIEW

**Comment by aspires** [comment]
cc @fastly/ux

**Comment by jamesarosen** [comment]
Thanks for contributing!

I like all of these. +1

**Comment by thejameskyle** [comment]
Ping. This would be nice to have up on a package manager. 

The steps for publishing on npm are here: https://docs.npmjs.com/getting-started/publishing-npm-packages

If the package name is an issue you can follow these steps to take over the `epoch` name: https://www.npmjs.com/policies/disputes

**Comment by jamesarosen** [comment]
Epoch isn't a CommonJS project and can't work with Node. The `package.json` is mostly for the purpose of installing development dependencies. I don't *mind* pushing it to NPM, but I worry that people will then expect it to work with Node.

**Comment by thejameskyle** [comment]
@jamesarosen You could wrap it in a UMD and distribute a compiled version.

**Comment by sompylasar** [comment]
@jamesarosen Please note that `npm` can be used to manage browser-side dependencies, too, by using `webpack` or `browserify`.

**Comment by jamesarosen** [comment]
I haven't used `webpack` or `browserify`. Do they work with CoffeeScript files like Epoch uses? Or, alternatively, do they work with the *globals*-style `epoch.js` and `epoch.min.js` that Epoch builds and includes?

**Comment by sompylasar** [comment]
I haven't used `browserify` myself, it has a slightly different goal than
`webpack`, so it might only work with CommonJS modules.

`webpack` can be configured with loaders very flexibly to load any way you
like: CoffeeScript or globals-style or CommonJS.

I used `webpack` with the globals-style distributable and an
`exports-loader` but in general this is not the best way to go. If epoch
used CommonJS modules, I could use its entry point via `webpack` without
additional configuration.

**Comment by jamesarosen** [comment]
@rsandor do you have any thoughts?

**Comment by rsandor** [comment]
@jamesarosen - I think it's probably okay to release as an npm module considering that it would make it easier for those using that for browser-side dependences. However, I am very much not sure what the best approach for this would be (as I am unfamiliar with the options listed).

Lets merge these changes now and consider `npm` in a separate issue for the time being. @thejameskyle or @sompylasar would either of you mind setting up a new github issue for this and outlining the proposed solutions?

**Pull request merged**
