### PR TITLE
Add hasOwnProperty guard

### PR DESCRIPTION
**Pull request by jamesarosen**
@duretti @rsandor @jadeapplegate @oso-mate

CoffeeScript's `for own x, y of z` adds a `hasOwnProperty` guard to the iteration. That's important in general, but particularly when `Array.prototype` has been extended.

### CODE REVIEW

**Comment by oso-mate** [comment]
Is that `own` to ensure only properties of the object, not the chain? I didn't know this was a thing, cool!

**Comment by jamesarosen** [comment]
```coffee
for x, y of z
  doSomething(x, y);
```
compiles to
```js
var x, y;

for (x in z) {
  y = z[x];
  doSomething(x, y);
}
```
whereas
```coffee
for own x, y of z
  doSomething(x, y);
```
compiles to
```js
var x, y,
  __hasProp = {}.hasOwnProperty;

for (x in z) {
  if (!__hasProp.call(z, x)) continue;
  y = z[x];
  doSomething(x, y);
}
```
`Object.prototype.hasOwnProperty` will ignore inherited properties.

**Comment by rsandor** [comment]
@jamesarosen - Good call. I'll run the basic and rendering tests myself to double check functionality.

**Comment by jamesarosen** [comment]
@rsandor ps: I'm having trouble with `cake test`; each test complains that `Epoch` is undefined.

**Comment by rsandor** [comment]
@jamesarosen - Sorry for the delay, that's very interesting. I am not sure why it is happening since I am able to run tests just fine on my end. When you run `cake build` on its own does it throw out any errors?

**Comment by rsandor** [comment]
@jamesarosen - Unit tests are passing just fine, heatmap rendering tests are broken in both your branch and master (thus unrelated to your changes). Gonna address those in another pull. Merging your changes now.

**Pull request merged**
